using System.Globalization;
using System.Resources;

namespace TweakOne.Properties;

internal static class Resources
{
    private static readonly ResourceManager ResourceManagerInstance = new("TweakOne.Properties.Resources", typeof(Resources).Assembly);

    public static CultureInfo? Culture { get; set; }

    public static string WindowTitle => GetString(nameof(WindowTitle));
    public static string CloneTabHeader => GetString(nameof(CloneTabHeader));
    public static string RectificationTabHeader => GetString(nameof(RectificationTabHeader));
    public static string CenteredRectificationTabHeader => GetString(nameof(CenteredRectificationTabHeader));
    public static string OpenSourcePackageButton => GetString(nameof(OpenSourcePackageButton));
    public static string NoSourceFileLoaded => GetString(nameof(NoSourceFileLoaded));
    public static string OpenTargetPackageButton => GetString(nameof(OpenTargetPackageButton));
    public static string SaveTargetPackageButton => GetString(nameof(SaveTargetPackageButton));
    public static string NoTargetFileLoaded => GetString(nameof(NoTargetFileLoaded));
    public static string SourceFieldHeader => GetString(nameof(SourceFieldHeader));
    public static string TargetFieldHeader => GetString(nameof(TargetFieldHeader));
    public static string SelectSourceField => GetString(nameof(SelectSourceField));
    public static string SelectTargetField => GetString(nameof(SelectTargetField));
    public static string GuidanceLinesHeader => GetString(nameof(GuidanceLinesHeader));
    public static string TargetGuidanceLinesHeader => GetString(nameof(TargetGuidanceLinesHeader));
    public static string PreviewZoomLabel => GetString(nameof(PreviewZoomLabel));
    public static string PreviewResetZoomButton => GetString(nameof(PreviewResetZoomButton));
    public static string PreviewPanHint => GetString(nameof(PreviewPanHint));
    public static string SourceGuidanceHint => GetString(nameof(SourceGuidanceHint));
    public static string TargetGuidanceHint => GetString(nameof(TargetGuidanceHint));
    public static string CloneControlsHeader => GetString(nameof(CloneControlsHeader));
    public static string CloneDesignatorLabel => GetString(nameof(CloneDesignatorLabel));
    public static string CloneDesignatorWatermark => GetString(nameof(CloneDesignatorWatermark));
    public static string TranslationOffsetMetersLabel => GetString(nameof(TranslationOffsetMetersLabel));
    public static string CloneAsIsButton => GetString(nameof(CloneAsIsButton));
    public static string CloneWithAutoTranslationButton => GetString(nameof(CloneWithAutoTranslationButton));
    public static string DeleteSelectedTargetGuidanceButton => GetString(nameof(DeleteSelectedTargetGuidanceButton));
    public static string UseSourceAsTargetButton => GetString(nameof(UseSourceAsTargetButton));
    public static string AutoTranslationDescription => GetString(nameof(AutoTranslationDescription));
    public static string RectificationControlsHeader => GetString(nameof(RectificationControlsHeader));
    public static string RectificationDesignatorLabel => GetString(nameof(RectificationDesignatorLabel));
    public static string RectificationDesignatorWatermark => GetString(nameof(RectificationDesignatorWatermark));
    public static string RectificationDesignatorRequiredError => GetString(nameof(RectificationDesignatorRequiredError));
    public static string RectificationOffsetMetersLabel => GetString(nameof(RectificationOffsetMetersLabel));
    public static string RectificationRowCountLabel => GetString(nameof(RectificationRowCountLabel));
    public static string RectificationApplicationOffsetMetersLabel => GetString(nameof(RectificationApplicationOffsetMetersLabel));
    public static string RectificationToleranceMetersLabel => GetString(nameof(RectificationToleranceMetersLabel));
    public static string RectificationPassModeLabel => GetString(nameof(RectificationPassModeLabel));
    public static string RectificationPassModeAutomaticLabel => GetString(nameof(RectificationPassModeAutomaticLabel));
    public static string RectificationPassModeManualLabel => GetString(nameof(RectificationPassModeManualLabel));
    public static string RectificationManualPassCountLabel => GetString(nameof(RectificationManualPassCountLabel));
    public static string RectificationAutomaticPassCountLabel => GetString(nameof(RectificationAutomaticPassCountLabel));
    public static string RectificationAutomaticPassCountNotAnalyzed => GetString(nameof(RectificationAutomaticPassCountNotAnalyzed));
    public static string RectificationToleranceGuidance => GetString(nameof(RectificationToleranceGuidance));
    public static string RectificationExportModeLabel => GetString(nameof(RectificationExportModeLabel));
    public static string RectificationExportModeSingleLabel => GetString(nameof(RectificationExportModeSingleLabel));
    public static string RectificationExportModeGroupedLabel => GetString(nameof(RectificationExportModeGroupedLabel));
    public static string RectificationExportModeTramlinesLabel => GetString(nameof(RectificationExportModeTramlinesLabel));
    public static string RectificationGroupedExportHint => GetString(nameof(RectificationGroupedExportHint));
    public static string AnalyzeRectificationButton => GetString(nameof(AnalyzeRectificationButton));
    public static string ApplyRectifiedGuidanceButton => GetString(nameof(ApplyRectifiedGuidanceButton));
    public static string RectificationResultHeader => GetString(nameof(RectificationResultHeader));
    public static string RectificationResultNotAnalyzed => GetString(nameof(RectificationResultNotAnalyzed));
    public static string RectificationDescription => GetString(nameof(RectificationDescription));
    public static string RectificationPreviewHint => GetString(nameof(RectificationPreviewHint));
    public static string CenteredRectificationPreviewHeader => GetString(nameof(CenteredRectificationPreviewHeader));
    public static string CenteredRectificationPreviewHint => GetString(nameof(CenteredRectificationPreviewHint));
    public static string CenteredRectificationControlsHeader => GetString(nameof(CenteredRectificationControlsHeader));
    public static string OpenCenteredRectificationTemplateButton => GetString(nameof(OpenCenteredRectificationTemplateButton));
    public static string ApplyCenteredRectificationTemplateButton => GetString(nameof(ApplyCenteredRectificationTemplateButton));
    public static string OpenCenteredRectificationTemplatePickerTitle => GetString(nameof(OpenCenteredRectificationTemplatePickerTitle));
    public static string SaveCenteredRectificationTemplatePickerTitle => GetString(nameof(SaveCenteredRectificationTemplatePickerTitle));
    public static string CenteredRectificationTemplateLabel => GetString(nameof(CenteredRectificationTemplateLabel));
    public static string CenteredRectificationAcceptedPackageLabel => GetString(nameof(CenteredRectificationAcceptedPackageLabel));
    public static string CenteredRectificationMarkerDistanceLabel => GetString(nameof(CenteredRectificationMarkerDistanceLabel));
    public static string CenteredRectificationMachineWidthLabel => GetString(nameof(CenteredRectificationMachineWidthLabel));
    public static string CenteredRectificationOffsetsHeader => GetString(nameof(CenteredRectificationOffsetsHeader));
    public static string CenteredRectificationNoTemplateLoaded => GetString(nameof(CenteredRectificationNoTemplateLoaded));
    public static string CenteredRectificationTemplateMissingPartfieldError => GetString(nameof(CenteredRectificationTemplateMissingPartfieldError));
    public static string CenteredRectificationNoPlanError => GetString(nameof(CenteredRectificationNoPlanError));
    public static string CenteredRectificationCorrectionLineCountError => GetString(nameof(CenteredRectificationCorrectionLineCountError));
    public static string CenteredRectificationNoAcceptedPackage => GetString(nameof(CenteredRectificationNoAcceptedPackage));
    public static string CenteredRectificationNotAvailable => GetString(nameof(CenteredRectificationNotAvailable));
    public static string CenteredRectificationMarkerALabel => GetString(nameof(CenteredRectificationMarkerALabel));
    public static string CenteredRectificationMarkerBLabel => GetString(nameof(CenteredRectificationMarkerBLabel));
    public static string StatusInitial => GetString(nameof(StatusInitial));
    public static string SaveTargetBeforeLoadingError => GetString(nameof(SaveTargetBeforeLoadingError));
    public static string SaveTargetPackagePickerTitle => GetString(nameof(SaveTargetPackagePickerTitle));
    public static string OpenSourcePackagePickerTitle => GetString(nameof(OpenSourcePackagePickerTitle));
    public static string OpenTargetPackagePickerTitle => GetString(nameof(OpenTargetPackagePickerTitle));
    public static string IsoXmlPackageFileType => GetString(nameof(IsoXmlPackageFileType));
    public static string DefaultTargetPackageFileName => GetString(nameof(DefaultTargetPackageFileName));
    public static string StatusLoadedSourcePackage => GetString(nameof(StatusLoadedSourcePackage));
    public static string StatusLoadedTargetPackage => GetString(nameof(StatusLoadedTargetPackage));
    public static string StatusSavedTargetPackage => GetString(nameof(StatusSavedTargetPackage));
    public static string StatusLoadedCenteredRectificationTemplate => GetString(nameof(StatusLoadedCenteredRectificationTemplate));
    public static string StatusAppliedCenteredRectificationTemplate => GetString(nameof(StatusAppliedCenteredRectificationTemplate));
    public static string SelectSourceGuidanceLineError => GetString(nameof(SelectSourceGuidanceLineError));
    public static string SelectTargetFieldError => GetString(nameof(SelectTargetFieldError));
    public static string SelectTargetGuidanceLineError => GetString(nameof(SelectTargetGuidanceLineError));
    public static string RectificationOffsetPositiveError => GetString(nameof(RectificationOffsetPositiveError));
    public static string RectificationTolerancePositiveError => GetString(nameof(RectificationTolerancePositiveError));
    public static string RectificationPassCountRangeErrorFormat => GetString(nameof(RectificationPassCountRangeErrorFormat));
    public static string StatusClonedGuidanceLine => GetString(nameof(StatusClonedGuidanceLine));
    public static string StatusClonedAndTranslatedGuidanceLine => GetString(nameof(StatusClonedAndTranslatedGuidanceLine));
    public static string StatusDeletedTargetGuidanceLine => GetString(nameof(StatusDeletedTargetGuidanceLine));
    public static string StatusAppliedRectifiedGuidanceLines => GetString(nameof(StatusAppliedRectifiedGuidanceLines));
    public static string StatusAppliedRectifiedGuidanceGroups => GetString(nameof(StatusAppliedRectifiedGuidanceGroups));
    public static string UnnamedField => GetString(nameof(UnnamedField));
    public static string PartfieldSummaryFormat => GetString(nameof(PartfieldSummaryFormat));
    public static string GuidancePathDefaultName => GetString(nameof(GuidancePathDefaultName));
    public static string GuidancePathNoPoints => GetString(nameof(GuidancePathNoPoints));
    public static string GuidancePathSummaryFormat => GetString(nameof(GuidancePathSummaryFormat));
    public static string GuidancePathCopyFormat => GetString(nameof(GuidancePathCopyFormat));
    public static string RectifiedGuidancePathFormat => GetString(nameof(RectifiedGuidancePathFormat));
    public static string RectifiedPositiveGuidancePathFormat => GetString(nameof(RectifiedPositiveGuidancePathFormat));
    public static string RectifiedNegativeGuidancePathFormat => GetString(nameof(RectifiedNegativeGuidancePathFormat));
    public static string RectifiedPositiveSmoothedGuidancePathFormat => GetString(nameof(RectifiedPositiveSmoothedGuidancePathFormat));
    public static string RectifiedNegativeSmoothedGuidancePathFormat => GetString(nameof(RectifiedNegativeSmoothedGuidancePathFormat));
    public static string RectifiedPositiveProgressiveGuidancePathFormat => GetString(nameof(RectifiedPositiveProgressiveGuidancePathFormat));
    public static string RectifiedNegativeProgressiveGuidancePathFormat => GetString(nameof(RectifiedNegativeProgressiveGuidancePathFormat));
    public static string PositiveDirectionLabel => GetString(nameof(PositiveDirectionLabel));
    public static string NegativeDirectionLabel => GetString(nameof(NegativeDirectionLabel));
    public static string RectificationCandidateSummaryFormat => GetString(nameof(RectificationCandidateSummaryFormat));
    public static string RectificationAcceptedSummaryFormat => GetString(nameof(RectificationAcceptedSummaryFormat));
    public static string RectificationAutomaticPassCountFormat => GetString(nameof(RectificationAutomaticPassCountFormat));
    public static string RectificationAutomaticPassCountUnsupportedFormat => GetString(nameof(RectificationAutomaticPassCountUnsupportedFormat));
    public static string CenteredRectificationSummaryFormat => GetString(nameof(CenteredRectificationSummaryFormat));
    public static string RectificationTramlinesExportNotAvailable => GetString(nameof(RectificationTramlinesExportNotAvailable));
    public static string RectificationTwoPassSummaryFormat => GetString(nameof(RectificationTwoPassSummaryFormat));
    public static string RectificationMultiPassSummaryFormat => GetString(nameof(RectificationMultiPassSummaryFormat));
    public static string RectificationRejectedSummaryFormat => GetString(nameof(RectificationRejectedSummaryFormat));
    public static string PackageNotFound => GetString(nameof(PackageNotFound));
    public static string PackageMissingTaskDataXml => GetString(nameof(PackageMissingTaskDataXml));
    public static string PackageInvalidTaskDataPath => GetString(nameof(PackageInvalidTaskDataPath));
    public static string GuidanceNeedsAtLeastTwoPointsError => GetString(nameof(GuidanceNeedsAtLeastTwoPointsError));
    public static string OnlyGuidancePathTypeError => GetString(nameof(OnlyGuidancePathTypeError));
    public static string TranslationNotSupportedAtPolesError => GetString(nameof(TranslationNotSupportedAtPolesError));
    public static string TranslationRequiresDistinctPointsError => GetString(nameof(TranslationRequiresDistinctPointsError));
    public static string CenteredRectificationTemplateVersionError => GetString(nameof(CenteredRectificationTemplateVersionError));

    private static string GetString(string name)
    {
        return ResourceManagerInstance.GetString(name, Culture) ?? name;
    }
}
